Controllers/AuthorsController.cs
using AutoMapper;
using Bookify.Web.Core.Models;
using Bookify.Web.Core.ViewModels;
using Bookify.Web.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookify.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public AuthorsController(ApplicationDbContext context , IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
           var authors =  _context.Authors.AsNoTracking().ToList();

            var authorsMappedc = _mapper.Map<IEnumerable<AuthorView>>(authors);
            return View(authorsMappedc);
        }

        [HttpGet]

        public IActionResult Create()
        {

            return PartialView("_AuthorForm");
        }

        [HttpPost]
        public IActionResult Create(AuthorViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = new Author
            {
                Name = model.Name
            };

            _context.Add(author);
            _context.SaveChanges();

            var AuthorMapping  = _mapper.Map<AuthorView>(author);

            return PartialView("_AuthorsRow", AuthorMapping);
        }


        //
        public IActionResult Edit(int id)
        {

            var author = _context.Authors.Find(id);

            if (author is null)
                return NotFound();

            var viewModel = new AuthorViewModel
            {
                Id = id,
                Name = author.Name

            };

            TempData["Message"] = "Save Successfully";


            return View("_AuthorForm", viewModel);
        }


        [HttpPost]
        public IActionResult Edit(AuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var author = _context.Authors.Find(model.Id);

                if (author is null)
                    return NotFound();

                author.Name = model.Name;
                author.LastUpdateDate = DateTime.Now;
                _context.SaveChanges();



                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggelStaures(int id)
        {
            var author = _context.Authors.Find(id);
            if (author is null)
                return NotFound();

            author.IsDeleted = !author.IsDeleted;
            var lastUodatedOn = author.LastUpdateDate = DateTime.Now;

            _context.SaveChanges();

            return Ok(lastUodatedOn.ToString());
        }



        public IActionResult AllowItem(AuthorViewModel model)
        {
            var author = _context.Authors.SingleOrDefault(C => C.Name == model.Name);



            var isAllow = author is null || author.Id == model.Id;

            return Json(isAllow);


        }


    }
}

Controllers/CategoriesController.cs
using AutoMapper;
using Bookify.Web.Core.Models;
using Bookify.Web.Core.ViewModels;
using Bookify.Web.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookify.Web.Controllers
{
	public class CategoriesController : Controller
	{
		private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CategoriesController( ApplicationDbContext context , IMapper mapper) 
        {
			_context = context;
            _mapper = mapper;
        }
        public IActionResult Index()
		{
			var category = _context.Categories.AsNoTracking().ToList();
			
			var MappedCate = _mapper.Map< IEnumerable<CategoryView>>(category);


			return View(MappedCate);
		}
		[HttpGet]	
		
		public IActionResult Create()
		{

			return PartialView("_Form");
		}

		[HttpPost]
		public IActionResult Create(CategoryViewModel model)
		{
			if (!ModelState.IsValid)
				return BadRequest();

			var categ = new Category
			{
				Name = model.Name
			};

			_context.Add(categ);
			_context.SaveChanges();

			var MappedCate = _mapper.Map<CategoryView>(categ);

			return PartialView("_CategoryRow" , MappedCate);
		}

		public IActionResult Edit( int id)
		{
		
			var categoty = _context.Categories.Find(id);

			if (categoty is null)
				return NotFound();

			var viewModel = new CategoryViewModel
			{
				Id = id,
				Name = categoty.Name

			};

            TempData["Message"] = "Save Successfully";


            return View("_form" , viewModel);
		}
	

		[HttpPost]
		public IActionResult Edit(CategoryViewModel model)
		{
			if (ModelState.IsValid)
			{
				var category = _context.Categories.Find(model.Id);

				if (category is null)
					return NotFound();

				category.Name = model.Name;
				category.LastUpdateDate = DateTime.Now;
				_context.SaveChanges();
			


				return RedirectToAction(nameof(Index));
			}

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult ToggelStaures(int id)
		{
			var category = _context.Categories.Find(id);
			if (category is null)
				return NotFound();

			category.IsDeleted = !category.IsDeleted;
			var lastUodatedOn = category.LastUpdateDate = DateTime.Now;

			_context.SaveChanges();

			return Ok(lastUodatedOn.ToString());		
		}



		public IActionResult AllowItem(CategoryViewModel model)
		{
			var category = _context.Categories.SingleOrDefault(C => C.Name == model.Name);



			var isAllow = category is null || category.id == model.Id;

			return Json(isAllow);


		}

	}
}

Controllers/HomeController.cs
using Bookify.Web.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookify.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Views/Authors/Create.cshtml
@model AuthorViewModel

@{
    ViewData["Title"] = "Add Author";
}
<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title" Add Author</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form method="post" asp-controller="Authors" asp-action="Create">

                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            @if (Model?.Id > 0)
                            {
                                <input type="hidden" asp-for="Id" />

                            }


                            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="bi bi-check2"></i>
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

}

Views/Authors/Edit.cshtml
@model AuthorViewModel

@{
    ViewData["Title"] = "Edit Author";
}

<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title" Edit Author</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form method="post" asp-controller="Authors" asp-action="Edit">

                    <div class="mb-5">
                        <div class="form-floating mb-2">



                            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="bi bi-check2"></i>
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

}

Views/Authors/Index.cshtml
 @model IEnumerable<AuthorView>

 @inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiKey

@{
    ViewData["Title"] = "AuthorsView";
}

@section CustomScripts {
    <link href="~/js/plugins/datatables/datatables.bundle.css" rel="stylesheet" />
}

<div class="alert bg-light-primary border border-primary border-dashed d-flex justify-content-between flex-sm-row w-100 p-5 mb-10">

    <div class="d-flex align-items-center">
        <div class="symbol symbol-40px d-flex  me-4">
            <div class="symbol-label fs-2 fw-semibold text-success">
                <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                <span class="svg-icon svg-icon-2 svg-icon-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
                        <path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
            </div>
        </div>
        <!--begin::Content-->

        <div class="d-flex flex-column pe-0 pe-sm-10 ">
            <h5 class="mb-1">Authors</h5>
        </div>

    </div>

    <!--end::Content-->

    <div>
        <a href="javascript:;" class="btn btn-sm btn-primary js-render-modal"
           data-title="Add Author" data-url="/Authors/Create">

            <i class="bi bi-plus-square-dotted  "></i>
            Add
        </a>
    </div>



</div>









<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title">

            Authors
        </h3>
        <div class="card-toolbar">
        </div>
    </div>
    <div class="card-body">

        @if (!Model.Any())
        {
            <div class="alert alert-dismissible bg-light-warning border border-warning border-dashed d-flex flex-column flex-sm-row w-100 p-5 mb-10">
                <!--begin::Icon-->
                <!--begin::Svg Icon | path: icons/duotune/communication/com003.svg-->
                <span class="svg-icon svg-icon-2hx svg-icon-warning me-4 mb-5 mb-sm-0">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor" />
                        <rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor" />
                        <rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
                <!--end::Icon-->
                <!--begin::Content-->
                <div class="d-flex flex-column pe-0 pe-sm-10 align-self-center">
                    <h5 class="mb-1">No categories found!</h5>
                </div>
                <!--end::Content-->
            </div>
        }
        else
        {
            <div class="table-responsive">

                <table class="table table-row-dashed  table-row-gray-300 ">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Stauts</th>
                            <th>Create On</th>
                            <th>Last Updated On</th>
                            <th>Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var author in Model)
                        {
                            <partial name="_AuthorsRow" model="@author" />

                        }
                    </tbody>


                </table>



            </div>


        }

    </div>

    <input hidden name="__RequestVerificationToken" value="@antiKey.GetAndStoreTokens(Context).RequestToken" />
    @section Plugin {
        <script src="~/js/plugins/datatables/datatables.bundle.js"></script>
    }



    @section Scripts {
        <partial name="_ValidationScriptsPartial" />


        <script>


        </script>



    }

Views/Authors/_AuthorForm.cshtml
@model AuthorViewModel

<form asp-action="@(Model?.Id > 0 ? "Edit" : "Create")"
      data-ajax-method="post"
      data-ajax="true"
      data-ajax-begin="onModelBegin"
      data-ajax-success="onModalSuccess"
      data-ajax-failure="ShowErrorMessage"
      data-ajax-compelet="onModalComplete">

    @if (Model?.Id > 0)
    {
        <input type="hidden" asp-for="Id" />
    }
    <div class="mb-5">
        <div class="form-floating mb-2">
            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
            <label asp-for="Name"></label>
        </div>
        <span asp-validation-for="Name" class="text-danger d-block"></span>
    </div>
    <partial name="_ModelFooter" />

</form>

Views/Authors/_AuthorsRow.cshtml
@model AuthorView

<tr>
    <td>@Model.Name</td>
    <td>
        <span class="badge badge-light-@(Model.IsDeleted ? "danger" : "success") js-stauts">
            @(Model.IsDeleted ? "Deleted" : "Available")
        </span>

    </td>
    <td>@Model.DateOfCreation</td>
    <td class="js-last-update">@Model.LastUpdateDate</td>
    <td>

        <button type="button" class="btn btn-sm btn-icon btn-color-primary btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
            <!--begin::Svg Icon | path: icons/duotune/general/gen024.svg-->
            <span class="svg-icon svg-icon-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="5" y="5" width="5" height="5" rx="1" fill="currentColor"></rect>
                        <rect x="14" y="5" width="5" height="5" rx="1" fill="currentColor" opacity="0.3"></rect>
                        <rect x="5" y="14" width="5" height="5" rx="1" fill="currentColor" opacity="0.3"></rect>
                        <rect x="14" y="14" width="5" height="5" rx="1" fill="currentColor" opacity="0.3"></rect>
                    </g>
                </svg>
            </span>
            <!--end::Svg Icon-->
        </button>


        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-3" data-kt-menu="true" style="">
            <!--begin::Menu item-->
            <div class="menu-item px-3">

                <a class="menu-link px-3 "
                   data-title="Edit Author" data-url="/Authors/Edit/@Model.id">
                    Edit
                </a>
            </div>
            <!--end::Menu item-->
            <!--begin::Menu item-->
            <div class="menu-item px-3">
                <a href="javascript:;"
                   class="menu-link flex-stack px-3 js-toggle-status"
                   data-url="/Authors/ToggelStaures/@Model.id">
                    Toggle Status
                </a>
            </div>
            <!--end::Menu item-->
        </div>





    </td>




</tr>

Views/Categories/Create.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = "Add Category";
}
<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title" Add Category</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form method="post" asp-controller="Categories" asp-action="Create">
                   
                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            @if(Model?.Id > 0)
                            {
                                <input type="hidden" asp-for="Id" />

                            }


                            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="bi bi-check2"></i>
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

}

Views/Categories/Edit.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = "Edit Category";
}

<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title" Edit Category</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form method="post" asp-controller="Categories" asp-action="Edit">

                    <div class="mb-5">
                        <div class="form-floating mb-2">



                            <input type="text" class="form-control" placeholder="Name" asp-for="Name" />
                            <label asp-for="Name"></label>
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="bi bi-check2"></i>
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

}

Views/Categories/Index.cshtml
 @model IEnumerable<CategoryView>

 @inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiKey

@{
    ViewData["Title"] = "CategriesView";
}
 
@section CustomScripts {
    <link href="~/js/plugins/datatables/datatables.bundle.css" rel="stylesheet" />
}

<div class="alert bg-light-primary border border-primary border-dashed d-flex justify-content-between flex-sm-row w-100 p-5 mb-10">
   
    <div class="d-flex align-items-center">
        <div class="symbol symbol-40px d-flex  me-4">
            <div class="symbol-label fs-2 fw-semibold text-success">
                <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                <span class="svg-icon svg-icon-2 svg-icon-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
                        <path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
            </div>
        </div>
        <!--begin::Content-->

        <div class="d-flex flex-column pe-0 pe-sm-10 ">
            <h5 class="mb-1">Categories</h5>
        </div>

</div>
  
        <!--end::Content-->
      
        <div>
        <a href="javascript:;" class="btn btn-sm btn-primary js-render-modal"
           data-title="Add Category" data-url="/Categories/Create">

            <i class="bi bi-plus-square-dotted  "></i>
            Add
        </a>
        </div>
      


</div>









<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title">
            
            Categories
            </h3>
        <div class="card-toolbar">
            
        </div>
    </div>
    <div class="card-body">

        @if (!Model.Any())
        {
            <div class="alert alert-dismissible bg-light-warning border border-warning border-dashed d-flex flex-column flex-sm-row w-100 p-5 mb-10">
                <!--begin::Icon-->
                <!--begin::Svg Icon | path: icons/duotune/communication/com003.svg-->
                <span class="svg-icon svg-icon-2hx svg-icon-warning me-4 mb-5 mb-sm-0">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor" />
                        <rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)" fill="currentColor" />
                        <rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
                <!--end::Icon-->
                <!--begin::Content-->
                <div class="d-flex flex-column pe-0 pe-sm-10 align-self-center">
                    <h5 class="mb-1">No categories found!</h5>
                </div>
                <!--end::Content-->
            </div>
        }
        else
        {
            <div class="table-responsive">

                <table class="table table-row-dashed  table-row-gray-300 ">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th >Stauts</th>
                            <th>Create On</th>
                            <th>Last Updated On</th>
                            <th>Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach( var category in Model)
                        {
                            <partial name="_CategoryRow" model="@category" />

                        }
                    </tbody>
                
                
                </table>



            </div>

           
        }

    </div>

    <input hidden name="__RequestVerificationToken" value="@antiKey.GetAndStoreTokens(Context).RequestToken" />
@section Plugin {
    <script src="~/js/plugins/datatables/datatables.bundle.js"></script>
    }



@section Scripts{
        <partial name="_ValidationScriptsPartial" />
       
        
<script>


        </script>



}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Aside.cshtml
<!--begin::Aside-->
<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
	<!--begin::Aside menu-->
	<div class="aside-menu flex-column-fluid px-4">
		<!--begin::Aside Menu-->
		<div class="hover-scroll-overlay-y my-5 pe-4 me-n4" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="{default: '#kt_aside_footer', lg: '#kt_header, #kt_aside_footer'}" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="{default: '5px', lg: '75px'}">
			<!--begin::Menu-->
			<div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6" id="#kt_aside_menu" data-kt-menu="true">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link " href="/">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M11 2.375L2 9.575V20.575C2 21.175 2.4 21.575 3 21.575H9C9.6 21.575 10 21.175 10 20.575V14.575C10 13.975 10.4 13.575 11 13.575H13C13.6 13.575 14 13.975 14 14.575V20.575C14 21.175 14.4 21.575 15 21.575H21C21.6 21.575 22 21.175 22 20.575V9.575L13 2.375C12.4 1.875 11.6 1.875 11 2.375Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Home</span>
					</a>
					<!--end:Menu link-->
					<a class="menu-link " asp-controller="Categories" asp-action="Index">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
									<path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Categries</span>
					</a>


					<a class="menu-link " asp-controller="Authors" asp-action="Index">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
									<i class="fa fa-user"></i>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Authors</span>
					</a>

					<!--end:Menu link-->
				
				
				
				</div>
				<!--end:Menu item-->
			</div>
			<!--end::Menu-->
		</div>
	</div>
	<!--end::Aside menu-->
</div>
<!--end::Aside-->

Views/Shared/_ModelFooter.cshtml
<div class="modal-footer px-0">
	<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	<button type="submit" class="btn btn-primary">Save</button>
</div>